### ISSUE TITLE
New Airdrop HIP-904 functions not part of precompile on main branch

### ISSUE THREAD

**Issue by jaycoolh** [hashgraph/hedera-smart-contracts#1135]
### Description

Functions introduced by HIP-904, such as `airdropTokens` are not included in the precompile smart contract in the main branch

They are listed in this branch: https://github.com/hashgraph/hedera-smart-contracts/blob/token-airdrop-e2e-tests/contracts/system-contracts/hedera-token-service/HederaTokenService.sol

But not in main branch https://github.com/hashgraph/hedera-smart-contracts/blob/main/contracts/system-contracts/hedera-token-service/HederaTokenService.sol

### Steps to reproduce

Go to links above

### Version

NA

### Operating system

None

**Comment by quiet-node** [comment]
Hi @jaycoolh, thank you for the report! This issue should be resolved in the following PR: https://github.com/hashgraph/hedera-smart-contracts/pull/1103.

The methods for HIP-904 can be found in these interfaces:
	•	[IHRC904.sol](https://github.com/hashgraph/hedera-smart-contracts/blob/main/contracts/system-contracts/hedera-token-service/IHRC904.sol)
	•	[IHRC904TokenFacade.sol](https://github.com/hashgraph/hedera-smart-contracts/blob/main/contracts/system-contracts/hedera-token-service/IHRC904TokenFacade.sol)

**Comment by jaycoolh** [comment]
@quiet-node I still don't see the `airdropToken, cancelAirdrop etc` functions inside of the main branch Hedera Precompile SC

https://github.com/hashgraph/hedera-smart-contracts/blob/main/contracts/system-contracts/hedera-token-service/HederaTokenService.sol
